name: Ktor CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: adopt
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
      - name: Gradle Test
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: test
